name: Artifact React app
permissions:
  contents: write
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Node.js v18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Test
        run: npm run test > test.txt
      - name: Upload Test
        uses: actions/upload-artifact@v4
        with: 
            name: testing
            path: test.txt
  download-test:
    runs-on: ubuntu-latest
    needs: test
    steps:
       - name: DownloadTest
         uses: actions/download-artifact@v4
         with:
            name: testing
       - name: Print Result
         shell: bash
         run: |
            value = `cat test.txt`
            echo "$value"
